Add macro declaration grammar, tests and highlights
JamesDoingStuff/tree-sitter-topas pull request #8
Opened 2024-10-17 07:55 UTC by JamesDoingStuff

Implement the `macro` preprocessor directive, which is used to create new macros. A macro declaration uses the format:
`macro Macro_name( parameters ) { body }`
with the following notes:
- The parameters field (including the parentheses) is entirely optional.
- An ampersand `&` can optionally precede the `Macro_name` and/or any of the `parameters`. This signals to the TOPAS preprocessor that the macro/parameters should be inlined into the code within parentheses.
- The body can contain code that would otherwise be syntactically invalid, such as expressions outside the equation format.

2024-10-18 09:08 UTC, garryod requested changes
Looks good except the commented out `'macro'` rule, would suggest it should either be included or removed entirely

2024-10-18 09:08 UTC, garryod commented on tree-sitter-topas/grammar.js
> +      // 'macro',
Is there a reason we're leaving this commented out?

2024-10-21 13:10 UTC, garryod approved these changes
Looks good, just a few odd bits of formatting

2024-10-21 13:10 UTC, garryod commented on tree-sitter-topas/grammar.js
> +
Is this an extra new line just for fun? :stuck_out_tongue:

2024-10-21 13:10 UTC, garryod commented on tree-sitter-topas/grammar.js
> +    ),
Interesting spacing :sweat_smile:

2024-10-21 13:29 UTC, JamesDoingStuff commented on tree-sitter-topas/grammar.js
> +    ),
Fixed it :grin:

2024-10-21 13:31 UTC, merged